version: '3.9'

services:
  users:
    build:
      context: ./
    container_name: users
    ports:
      - '9091:9091'
    links:
      - kafka
      - postgres
  feeds:
    build:
      context: ./
    container_name: feeds
    ports:
      - '9090:9090'
    links:
      - kafka
      - postgres
      - users
    command:
      - "/opt/app/feeds-0.0.1-SNAPSHOT.jar"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: Chidori
  ui:
    build:
      context: ./feed-reader-ui/
    container_name: feed-reader-ui
    ports:
      - '3000:3000'
    depends_on:
      - feeds
      - users

